name: Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis.yml"

jobs:
  jarvis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
        # /////////////////////////////////////////////////////////////////////////////////////////////////////
        # ///                                                                                               ///
        # ///   Using an existing GitHub Action from the marketplace makes it a powerfull CI/CD ecosystem.  ///
        # ///   However, power is always dangerous. That's why we need to decide wisely.                    ///
        # ///   Here are some helpfull tips.                                                                ///
        # ///                                                                                               ///
        # ///   0. For simple things, try not to use any external GitHub Action from the marketplace.       ///
        # ///   1. When you have to, in the marketplace use GitHub Action from Verified Creators            ///
        # ///      https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions  ///
        # ///   2. Use the latest and greatest version of existing GitHub Actions                           ///
        # ///   3. Think about GitHub Actions like dependencies. It needs to be maintained and updated      ///
        # ///   4. Have a proper PR process to avoid someone adding a malicious GitHub Action               ///
        # ///   5. Think about disabling or limiting GitHub Actions in your organization in the Settings    ///
        # ///                                                                                               ///
        # /////////////////////////////////////////////////////////////////////////////////////////////////////
      - name: Check GitHub Status
        run: |
          curl https://www.githubstatus.com/api/v2/status.json
