# ////////////////////////////////////////////////////////////
# ///                                                      ///
# ///   0. Take some time to understand the GitHub Action  /// 
# ///   1. Review the code. Can you spot the bug?          ///
# ///   2. Fix the pipeline and push to jarvis.yml         ///
# ///   3. Check the pipeline if passing then CONGRATS!    ///
# ///   4. If stuck then read the hint                     ///
# ///   5. Compare your solution with solution.yml         ///
# ///                                                      ///
# ////////////////////////////////////////////////////////////

name: Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis.yml"

jobs:
  jarvis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Check GitHub Status
        uses: dduzgun-security/secure-code-game-action@dc70b85ad674f6e93657401f3933622870372093 # v1.0
        with:
          who-to-greet: "Jarvis, obviously ..."
          get-token: "token-4db56ee8-dbec-46f3-96f5-32247695ab9b"
